K8s filestorage bastion
nebius/nebius-architect-solution-library pull request #30
Opened 2024-05-29 14:01 UTC by d3vil-st

2024-05-30 08:11 UTC, malibora requested changes

2024-05-30 08:11 UTC, malibora commented on kubernetes/terraform/kubernetes-filestore/bastion.tf
Please make this a standalone module we can reuse in any other k8s terraform solution. As an example you can have a look at loki module I am working on at the moment: https://github.com/nebius/nebius-architect-solution-library/tree/feature/log-aggregation/kubernetes/terraform/loki

Then in this k8s-fileshare, we can introduce it in main.tf, something like:

module "bastion" {
  providers = {
    nebius = nebius
  }
  count = var.bastion? 1:0
  folder_id = var.folder_id
  ...

}

2024-05-30 16:40 UTC, d3vil-st commented on kubernetes/terraform/kubernetes-filestore/bastion.tf
Done.

2024-05-31 08:37 UTC, malibora requested changes

2024-05-31 08:37 UTC, malibora commented on kubernetes/terraform/kubernetes-filestore/main.tf
Pls uncomment kubernetes-training, and comment kubernetes-inference

2024-05-31 08:37 UTC, malibora commented on kubernetes/terraform/kubernetes-filestore/terraform.tfvars
pls set explicitly node_count to 2... clients wont be aware of this if not visible in tfvars...

2024-05-31 14:38 UTC, malibora approved these changes

2024-05-31 14:40 UTC, merged